name: Stable

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Parse changelog
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          awk -v ver="$VERSION" '
          /^= / {
            if ($0 ~ "= " ver " =") {
              found=1;
              next
            }
            else if (found && /^= [0-9]/) {
              exit
            }
          }
          found && /^\*/ { print }
          ' readme.txt > changelog.txt
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Install JS dependencies and build
        run: |
          yarn install
          yarn build
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SLUG: ${{ secrets.SLUG }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog.txt
          files: ${{github.workspace}}/${{ secrets.SLUG }}.zip
