name: Stable

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Parse changelog
        id: changelog
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          START="= ${VERSION} ="
          END="= [0-9]+\.[0-9]+\.[0-9]+ =|==|\$"
          
          # Extract changelog for this version and convert to markdown
          grep -oPz "(?s)${START}.*?\n\K.*?(?=${END})" readme.txt | \
          sed 's/^\* \[\([^]]*\)\]/- **\1**:/g' > changelog.md
          
          # Remove last newline to clean up output
          truncate -s-1 changelog.md 2>/dev/null || true
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SLUG: ${{ secrets.SLUG }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog.md
          files: ${{github.workspace}}/${{ secrets.SLUG }}.zip